### ISSUE TITLE
php conflicts with the standalone nginx module

### ISSUE THREAD

**Issue by contyk** [modularity-modules/php#1]
I keep wondering why nginx is bundled with this module, effectively conflicting with the `nginx` module. Is that intentional?

**Comment by mkocka** [comment]
It was from historical reasons when there was no nginx module and we forget to change that, I am already rebuilding php without nginx.

**Comment by phracek** [comment]
@mkocka: Did you solve it already? Can we close the issue?

**Comment by mkocka** [comment]
This is solved already
