### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by tdawson** [modularity-modules/php#2]
The php module is missing some dependencies.

package: php-dba-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libtokyocabinet.so.9()(64bit)
  Recommended resolution:
    - install tokyocabinet

package: php-devel-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     autoconf
     automake
  Recommended resolution:
    - Filter our php-devel

package: php-enchant-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libenchant.so.1()(64bit)
  Recommended resolution:
    - enchant

package: php-gd-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libXpm.so.4()(64bit)
     libgd.so.3()(64bit)
  Recommended resolution:
    - gd libXpm libwebp

package: php-imap-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libc-client.so.2007()(64bit)
  Recommended resolution:
    - libc-client

package: php-interbase-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libfbclient.so.2()(64bit)
  Recommended resolution:
    - libfbclient2

package: php-mcrypt-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libmcrypt.so.4()(64bit)
  Recommended resolution:
    - libmcrypt

package: php-odbc-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libodbc.so.2()(64bit)
  Recommended resolution:
    - unixODBC

package: php-pdo-dblib-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libsybdb.so.5()(64bit)
  Recommended resolution:
    - freetds unixODBC

package: php-pspell-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libaspell.so.15()(64bit)
     libpspell.so.15()(64bit)
  Recommended resolution:
    - aspell

package: php-recode-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     librecode.so.0()(64bit)
  Recommended resolution:
    - recode

package: php-snmp-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libnetsnmp.so.30()(64bit)
     net-snmp
  Recommended resolution:
    - net-snmp net-snmp-libs

package: php-tidy-7.1.6-1.module_5b571866.x86_64
  unresolved deps: 
     libtidy.so.5()(64bit)
  Recommended resolution:
    - libtidy

**Comment by tdawson** [comment]
After looking at the yaml again, and then at these dependencies, I think it would be best to just filter out all of these extra php rpms.

**Comment by tdawson** [comment]
`diff --git a/php.yaml b/php.yaml
index 3c085c5..c0f0140 100644
--- a/php.yaml
+++ b/php.yaml
@@ -38,6 +38,21 @@ data:
     api:
         rpms:
                 - php
+    filter:
+        rpms:
+                - php-dba
+                - php-devel
+                - php-enchant
+                - php-gd
+                - php-imap
+                - php-interbase
+                - php-mcrypt
+                - php-odbc
+                - php-pdo-dblib
+                - php-pspell
+                - php-recode
+                - php-snmp
+                - php-tidy
     components:
         rpms:
             php:
`

**Comment by r4f4** [comment]
Another issue is that it adds gperftools which is already included by shared-userspace.

**Comment by mkocka** [comment]
I removed gperftools and add filter part

**Comment by mkocka** [comment]
php is in the build state

**Comment by mkocka** [comment]
... and it is done, I am closing this

**Comment by r4f4** [comment]
Thank you for the fix.
