### ISSUE TITLE
Dependencies already in base-runtime

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/php#4]
I don't know whether this is a false-positive or not, but php includes the following packages already in base-runtime:
`libmnl`
`libnetfilter_conntrack`
`libnfnetlink`
`libunwind`

**Comment by mkocka** [comment]
Hi thanks, I am going to remove it. 
Just a question, this is like the 3rd wave of these issues and I am wondering why are you discovering this now? May I somehow help to prevent this?

**Comment by mkocka** [comment]
Removed, there are only 3 packages left in components: 
 libxkbcommon, mailcap, xkeyboard-config

"id": 701

**Comment by r4f4** [comment]
This was just a follow-up from trying to fix the problems reported by repoclosure. As I commented in the mariadb issue, we need to discuss a non-manual way to prevent this.

**Comment by nphilipp** [comment]
This is fixed meanwhile.
